#On indique la source des dependances sur Github qu'on souhaite utiliser dans le projet
dependencies:
  # - <NomOrganisation/NomRepo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
dotenv: .env
#La gestion des clees privees
wallets:
  from_key: ${PRIVATE_KEY}

#On ajoute une section pour la gestion des reseaux
networks:
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
#On ajoute cette section pour definir la direction de "@chainlink"
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
